# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_prestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='prestado',
        ),
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
