# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20171116_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
