# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0005_auto_20171116_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField(auto_now=True)),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('estaus', models.CharField(choices=[('a', 'Activo'), ('c', 'Cerrado')], default='a', max_length=8)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
