# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_prestamo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='estaus',
            new_name='estatus',
        ),
    ]
