# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20171106_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='numero_empleado',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='puesto',
        ),
    ]
